In [1]:
import os
import numpy as np
import pandas as pd


In [2]:
root = './data/wechat_algo_data1'
train_data = pd.read_csv(os.path.join(root, 'user_action.csv')).astype(int)

print(train_data)

         userid  feedid  date_  device  read_comment  comment  like    play  \
0             8   71474      1       1             0        0     1     500   
1             8   73916      1       1             0        0     0     250   
2             8   50282      1       1             0        0     0     750   
3             8   11391      1       1             0        0     1    3750   
4             8   27349      1       1             0        0     0     250   
...         ...     ...    ...     ...           ...      ...   ...     ...   
7317877  250236   72813     12       2             0        0     0    6369   
7317878  250236   52019     12       2             0        0     0   13212   
7317879  250236   51045     12       2             0        0     0       0   
7317880  250236   46881     12       2             0        0     0       0   
7317881  250236   53804     12       2             1        0     0  160560   

           stay  click_avatar  forward  follow  fav

In [3]:
drop_columns = ['date_', 'device', 'comment', 'play', 'stay', 'follow', 'favorite']

train_data = train_data.drop(columns=drop_columns)
print(train_data.head())


   userid  feedid  read_comment  like  click_avatar  forward
0       8   71474             0     1             0        0
1       8   73916             0     0             0        0
2       8   50282             0     0             0        0
3       8   11391             0     1             0        0
4       8   27349             0     0             0        0


In [4]:
cols = ['userid', 'feedid', 'read_comment', 'like', 'click_avatar', 'forward']
drop_columns = ['date_', 'device', 'comment', 'play', 'stay', 'follow', 'favorite']

root = './data/wechat_algo_data1'

train_data = pd.read_csv(os.path.join(root, 'user_action.csv')).drop(columns=drop_columns).astype(int)
print(train_data.head())

   userid  feedid  read_comment  like  click_avatar  forward
0       8   71474             0     1             0        0
1       8   73916             0     0             0        0
2       8   50282             0     0             0        0
3       8   11391             0     1             0        0
4       8   27349             0     0             0        0


In [6]:
n_user, n_item = train_data[['userid', 'feedid']].max()

print(n_user, n_item)


250236 112871


In [7]:
# pytorch package
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader


class MovieLens(Dataset):
    def __init__(self, df):
        self.df_values = df.values

    def __getitem__(self, idx):
        _userid, _feedid, _read_comment, _like, _click_avatar, _forward = self.df_values[idx]

        return torch.LongTensor([_userid]), torch.LongTensor([_feedid]), torch.ShortTensor([_read_comment]), torch.ShortTensor([_like]), torch.ShortTensor([_click_avatar]), torch.ShortTensor([_forward])

    def __len__(self):
        return len(self.df_values)

# dataset
train_loader = DataLoader(MovieLens(train_data),
                          batch_size=16,
                          shuffle=True,

                          num_workers=0)

In [10]:
MovieLens(train_data).__getitem__(1)


(tensor([8]),
 tensor([73916]),
 tensor([0], dtype=torch.int16),
 tensor([0], dtype=torch.int16),
 tensor([0], dtype=torch.int16),
 tensor([0], dtype=torch.int16))

In [11]:
print(bin(250236))


0b111101000101111100


In [12]:
print(train_data[['userid', 'feedid']].min())


userid    8
feedid    0
dtype: int64


In [14]:
print(pd.DataFrame([[14, 67]]))

    0   1
0  14  67
